username: ./cloudseed-out
password: $6$ee735afb566102eb$g7nSXCk7qSySmh/7EEuftP41wZ9Xb0M4bGstiuPieDXcjL.h5fZ6wa7Qo.5/.RpcYkT9YQ2nqS/91HY.792RU1
groups: Administrators
first_logon_behaviour: always
inject_user_password: True
plugins: cloudbaseinit.plugins.common.sethostname.SetHostNamePlugin,cloudbaseinit.plugins.common.createuser.CreateUserPlugin,cloudbaseinit.plugins.common.setuserpassword.SetUserPasswordPlugin,cloudbaseinit.plugins.common.sshpublickeys.SetUserSSHPublicKeysPlugin,cloudbaseinit.plugins.common.networkconfig.NetworkConfigPlugin,cloudbaseinit.plugins.common.ntpclient.SetNtpClientPlugin,cloudbaseinit.plugins.common.localscripts.LocalScriptsPlugin
local_scripts_path: C:\Program Files\Cloudbase Solutions\Cloudbase-Init\LocalScripts
allow_reboot: True
metadata_services: cloudbaseinit.metadata.services.winrmconfigdrive.WinRmConfigDrive
