username: ./cloudseed-out
password: $6$c04f6b969159f626$4JC.NLe7MO6XIIy8lr9qDYDo7JPgazisytnZv8OREeKKLhlXG4AIRLY0SSvuFHzMF/wKlF8bSIufxEDWSzUes0
groups: Administrators
first_logon_behaviour: always
inject_user_password: True
plugins: cloudbaseinit.plugins.common.sethostname.SetHostNamePlugin,cloudbaseinit.plugins.common.createuser.CreateUserPlugin,cloudbaseinit.plugins.common.setuserpassword.SetUserPasswordPlugin,cloudbaseinit.plugins.common.sshpublickeys.SetUserSSHPublicKeysPlugin,cloudbaseinit.plugins.common.networkconfig.NetworkConfigPlugin,cloudbaseinit.plugins.common.ntpclient.SetNtpClientPlugin,cloudbaseinit.plugins.common.localscripts.LocalScriptsPlugin
local_scripts_path: C:\Program Files\Cloudbase Solutions\Cloudbase-Init\LocalScripts
allow_reboot: True
metadata_services: cloudbaseinit.metadata.services.configdrive.ConfigDrive
